In [113]:
# 导入包
import numpy as np

In [114]:
# 创建一维数组 [-5, 5]
a_1D_array = np.arange(-5, 5 + 1)
a_1D_array  # 查看数组内容

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [115]:
a_1D_array.shape  # 查看数组的形状

(11,)

In [116]:
a_1D_array.ndim # 查看数组的维度

1

In [117]:
len(a_1D_array)  # 查看数组的长度

11

### 索引 

In [118]:
# 索引数组的第一个元素
a_1D_array[0] 

np.int64(-5)

In [119]:
a_1D_array[-11]  # 索引数组的第一个元素，索引 -len(a_1D_array)

np.int64(-5)

In [120]:
# 索引数组的最后一个元素，索引为 -1 或 len(a_1D_array) - 1
a_1D_array[-1]

np.int64(5)

### 行向量、列向量

行向量、列向量都被视作特殊的二维数组。也就是说，行向量是一
行多列矩阵，而列向量是多行一列矩阵。

`numpy.newaxis` 是一个特殊的索引，用于增加数组的维度。它的作用是在数组
的某个位置添加一个新的轴，从而改变数组的维度

In [121]:
# 转为列向量
a_1D_array[:, np.newaxis]

array([[-5],
       [-4],
       [-3],
       [-2],
       [-1],
       [ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5]])

In [122]:
# 升维了
a_1D_array[:, np.newaxis].ndim

2

In [123]:
a_1D_array[:, None]  # None 和 np.newaxis 是等价的

array([[-5],
       [-4],
       [-3],
       [-2],
       [-1],
       [ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5]])

numpy.squeeze() 函数用于从数组的形状中删除长度为 1 的维度，并返回一个新的数组，其维度数目更少

例如，对于一个形状为 (1, 3, 1, 5) 的四维数组，可以使用 numpy.squeeze(a) 函数将其转换为形状为 (3, 5) 的二维数组，其中长度为 1 的第 0 和第 2 维被删除。

如果在调用 numpy.squeeze() 时指定了参数 axis，则只有该轴上长度为 1 的维度会被删除

In [124]:
a_1D_array.reshape(-1,1) # 也可以使用 reshape 方法来转换为列向量

array([[-5],
       [-4],
       [-3],
       [-2],
       [-1],
       [ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5]])

In [125]:
a_1D_array[:, np.newaxis].squeeze() # squeeze 方法可以去掉维度为1的轴

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [126]:
a_1D_array[np.newaxis, :]  # 转为行向量

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5]])

In [127]:
a_1D_array[None, :]  # None 和 np.newaxis 是等价的

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5]])

In [128]:
a_1D_array.reshape(1,-1) # 也可以使用 reshape 方法来转换为行向量

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5]])

### 切片

#### 获取数组中的前五个元素

In [129]:
# 切片数组的前5个元素
a_1D_array[:5]  # 前5个元素

array([-5, -4, -3, -2, -1])

In [130]:
a_1D_array[0:5] # 前5个元素，和上面等价

array([-5, -4, -3, -2, -1])

In [131]:
a_1D_array[[0,1,2,3,4]] # 前5个元素，和上面等价

array([-5, -4, -3, -2, -1])

和 Python 的列表切片类似，倒数第 n 个元素的索引为 -n，步长也同样可以使用。

### 整数索引

In [132]:
# 获取，第一、二 三，和最后一个元素
a_1D_array[[0, 1, 2, -1]]

array([-5, -4, -3,  5])

In [133]:
a_1D_array[np.r_[0:3, -1]]

# numpy.r_ 是一个用于将切片对象转换为一个沿着第一个轴堆叠的 NumPy 数组的函数。
# 它可以在数组创建和索引时使用。
# 它的作用类似于 numpy.concatenate 和 numpy.vstack，
# 但是使用切片对象作为索引来方便快捷地创建数组。

array([-5, -4, -3,  5])

In [134]:
# 或者采用合并
first_three = a_1D_array[:3]   # 获取前三个元素
last_one    = a_1D_array[-1:]  # 获取最后一个元素
np.concatenate((first_three[:3], last_one[-1:]))

array([-5, -4, -3,  5])

### 布尔索引

In [135]:
# 大于 1 的元素
bool_greater_than_1 = a_1D_array > 1
bool_greater_than_1

array([False, False, False, False, False, False, False,  True,  True,
        True,  True])

In [ ]:
a_1D_array[bool_greater_than_1]

In [ ]:
a_1D_array[a_1D_array > 1]  # 也可以直接使用布尔表达式作为索引