In [145]:
import numpy as np

In [146]:
A_2D = np.array([[-7, -6, -5, -4, -3],
                 [-2, -1, 0, 1, 2],
                 [3, 4, 5, 6, 7]])

### 索引

In [147]:
A_2D[0, 0]  # 第一行第一列元素

np.int64(-7)

In [148]:
type(A_2D[0, 0])  # numpy.int64

numpy.int64

In [149]:
type(A_2D[[0], [0]])  # numpy.ndarray

numpy.ndarray

In [150]:
A_2D[1, 2]  # 0 第一行第二列元素

np.int64(0)

In [151]:
A_2D[[1], [2]]  # array([0]) 第一行第二列元素，注意返回的是一个一维数组

array([0])

### 取出行

In [152]:
# 取出第一行，结果为一维向量
A_2D[0]  # array([-7, -6, -5, -4, -3])

array([-7, -6, -5, -4, -3])

In [153]:
A_2D[0, :]  # array([-7, -6, -5, -4, -3]) 第一行

array([-7, -6, -5, -4, -3])

In [154]:
A_2D[1]  # array([-2, -1,  0,  1,  2]) 第二行

array([-2, -1,  0,  1,  2])

In [155]:
A_2D[1, :]  # array([-2, -1,  0,  1,  2]) 第二行

array([-2, -1,  0,  1,  2])

In [156]:
# 取出第一行，结果为二维行向量
A_2D[[0], :]  # array([[-7, -6, -5, -4, -3]]) 第一行

array([[-7, -6, -5, -4, -3]])

In [157]:
A_2D[0, np.newaxis]  # array([[-7, -6, -5, -4, -3]]) 第一行

array([[-7, -6, -5, -4, -3]])

In [158]:
A_2D[[0, 2]]
# array([[-7, -6, -5, -4, -3],
#        [ 3,  4,  5,  6,  7]]) # 第一行和第三行

array([[-7, -6, -5, -4, -3],
       [ 3,  4,  5,  6,  7]])

In [159]:
A_2D[[0, 2], :]
# array([[-7, -6, -5, -4, -3],
#        [ 3,  4,  5,  6,  7]]) # 第一行和第三行

array([[-7, -6, -5, -4, -3],
       [ 3,  4,  5,  6,  7]])

### 取出列

In [160]:
A_2D[:, 0]  # array([-7, -2,  3]) 第一列

array([-7, -2,  3])

In [161]:
A_2D[..., 0]  # array([-7, -2,  3]) 第一列

array([-7, -2,  3])

In [162]:
A_2D[:, [0]]
# array([[-7],
#        [-2],
#        [ 3]]) # 第一列，结果为二维列向量

array([[-7],
       [-2],
       [ 3]])

In [163]:
A_2D[np.newaxis, :, 0]  # array([[-7, -2,  3]]) 第一列，结果为二维行向量

array([[-7, -2,  3]])

In [164]:
A_2D[:, 1]  # array([-6, -1,  4]) 第二列

array([-6, -1,  4])

In [165]:
A_2D[:, [0, 2, 4]]
# array([[-7, -5, -3],
#        [-2,  0,  2],
#        [ 3,  5,  7]]) # 第一列、第三列和第五列

array([[-7, -5, -3],
       [-2,  0,  2],
       [ 3,  5,  7]])

In [166]:
A_2D[:, 0::2]
# array([[-7, -5, -3],
#        [-2,  0,  2],
#        [ 3,  5,  7]]) # 第一列、第三列和第五列

array([[-7, -5, -3],
       [-2,  0,  2],
       [ 3,  5,  7]])

### 取出特定行列组合

In [167]:
A_2D[1, 2::]  # array([0, 1, 2]) # 第二行从第三列开始到最后一列

array([0, 1, 2])

In [168]:
A_2D[np.newaxis, 1,2::] # array([[0, 1, 2]]) # 第二行从第三列开始到最后一列，结果为二维行向量

array([[0, 1, 2]])

In [169]:
A_2D[1,2::, np.newaxis]
# array([[0],
#        [1],
#        [2]]) # 第二行从第三列开始到最后一列，结果为二维列向量

array([[0],
       [1],
       [2]])

In [170]:
A_2D[1::,[0,2,4]] 
# array([[-2,  0,  2],
#        [ 3,  5,  7]]) # 第二行和第三行的第一列、第三列和第五列

array([[-2,  0,  2],
       [ 3,  5,  7]])

In [171]:
A_2D[1::,0::2] 
# array([[-2,  0,  2],
#        [ 3,  5,  7]]) # 第二行和第三行的第一列、第三列和第五列

array([[-2,  0,  2],
       [ 3,  5,  7]])

In [172]:
A_2D[::2,:-1:2]
# array([[-7, -5],
#        [ 3,  5]]) # 第一行和第三行的第一列和第三列

array([[-7, -5],
       [ 3,  5]])

In [ ]:
# 二次切片
A_2D[:,[0,2]][[0, 2], :]
# array([[-7, -5],
#        [ 3,  5]]) # 第一列和第三列的第一行和第三行

In [ ]:
A_2D[[0, 2], :][:,[0,2]]
# array([[-7, -5],
#        [ 3,  5]]) # 第一行和第三行的第一列和第三列

#### 使用np.ix_()

In [ ]:
# np.ix_()函数将多个一维索引数组转换为一个用于多维数组索引的元组。这个元组可以用于同时对多个维度进行索引
A_2D[np.ix_([0, 2], [0, 2])]
# array([[-7, -5],
#        [ 3,  5]]) # 第一行和第三行的第一列和第三列