In [16]:
import numpy as np

In [17]:
A_3D = np.arange(-30, 30).reshape(3,4,5)
A_3D

array([[[-30, -29, -28, -27, -26],
        [-25, -24, -23, -22, -21],
        [-20, -19, -18, -17, -16],
        [-15, -14, -13, -12, -11]],

       [[-10,  -9,  -8,  -7,  -6],
        [ -5,  -4,  -3,  -2,  -1],
        [  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]],

       [[ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29]]])

In [18]:
A_3D[1] # 取第二个二维数组

array([[-10,  -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2,  -1],
       [  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [19]:
A_3D[1, 2] # 取第二个二维数组的第三行

array([0, 1, 2, 3, 4])

In [20]:
A_3D[:,0,:] # 取所有二维数组的第一行

array([[-30, -29, -28, -27, -26],
       [-10,  -9,  -8,  -7,  -6],
       [ 10,  11,  12,  13,  14]])

In [21]:
A_3D[:,:,0] # 取所有二维数组的第一列

array([[-30, -25, -20, -15],
       [-10,  -5,   0,   5],
       [ 10,  15,  20,  25]])

In [22]:
# 取出单一元素
A_3D[0, 0, 0]

np.int64(-30)

In [23]:
A_3D[[0], [0], [0]] # 等价于上面，但是返回的是一个数组

array([-30])

In [24]:
A_3D[0, -1, :] # 取第一个二维数组的最后一行

array([-15, -14, -13, -12, -11])

In [25]:
# 使用省略号
A_3D[1,...] # 等价于 A_3D[1,:,:]

array([[-10,  -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2,  -1],
       [  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [26]:
A_3D[...,1] # 等价于 A_3D[:,:,1]

array([[-29, -24, -19, -14],
       [ -9,  -4,   1,   6],
       [ 11,  16,  21,  26]])

In [27]:
# 使用take，返回的是视图
np.take(A_3D, [0,2], axis=1) # 取第一个和第三个二维数组

array([[[100, -29, -28, -27, -26],
        [-25, -24, -23, -22, -21],
        [-20, -19, -18, -17, -16],
        [-15, -14, -13, -12, -11]],

       [[-10,  -9,  -8,  -7,  -6],
        [ -5,  -4,  -3,  -2,  -1],
        [  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]],

       [[ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29]]])