In [1]:
import torch
import torch.nn as nn

In [2]:
# 输入数据
input = torch.randn(3, 2)
print(input)
# 得到预测概率值
pred = torch.sigmoid(input)
print(pred)

tensor([[ 0.2108, -1.0200],
        [-0.0496, -0.6198],
        [ 0.0142,  1.2326]])
tensor([[0.5525, 0.2650],
        [0.4876, 0.3498],
        [0.5036, 0.7743]])


In [3]:
# 目标值
target = torch.tensor([[0,1],[1,0],[0,1]], dtype=torch.float)
print(target)

tensor([[0., 1.],
        [1., 0.],
        [0., 1.]])


In [4]:
# 定义损失函数 二元交叉熵损失函数（常用于二分类问题）
loss = nn.BCELoss()
print(loss(pred, target)) # 预测概率值必须是 0 到 1 之间

tensor(0.7062)
