In [2]:
import torch
import numpy as np

# 基本张量创建

1) 按内容创建

In [3]:
# 传入标量
tensor1 = torch.tensor(10)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor(10)
torch.Size([])
torch.int64


In [4]:
# 传入一个一维数组
tensor2 = torch.tensor([1, 2.0, 3])
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)

tensor([1., 2., 3.])
torch.Size([3])
torch.float32


In [5]:
# 传入一个二维ndarray
tensor3 = torch.tensor(np.array([[1.0, 2, 3], [4, 5, 6]]))
print(tensor3)
print(tensor3.size())
print(tensor3.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.Size([2, 3])
torch.float64


2) 创建指定形状的张量

In [6]:
tensor1 = torch.Tensor(3, 2, 4)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)  # 数据类型默认 float32 类型

tensor([[[-2.4558e+24,  9.4307e-43,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])
torch.Size([3, 2, 4])
torch.float32


In [7]:
# Tensor 也可以用来创建指定内容的张量
tensor2 = torch.Tensor(np.array([[1.0, 2, 3], [4, 5, 6]]))
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)  # 数据类型默认 float32 类型

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
torch.float32


3) 创建指定类型的张量 (int32、int64、int16、int8、float32、float64、half、复数、bool)

In [8]:
# int (int32) 类型
tensor1 = torch.IntTensor(2, 3)
tensor2 = torch.tensor([2, 3], dtype=torch.int32)

print(tensor1.dtype)
print(tensor2.dtype)


torch.int32
torch.int32


In [9]:
# int (int64) 类型
tensor1 = torch.LongTensor(2, 3)
tensor2 = torch.tensor([2, 3], dtype=torch.long)

print(tensor1.dtype)
print(tensor2.dtype)

torch.int64
torch.int64


In [10]:
# float 类型
tensor1 = torch.FloatTensor(2, 3)
tensor2 = torch.tensor([2, 3], dtype=torch.float32)

print(tensor1.dtype)
print(tensor2.dtype)

torch.float32
torch.float32


In [11]:
# double (float64) 类型
tensor1 = torch.DoubleTensor(2, 3)
tensor2 = torch.tensor([2, 3], dtype=torch.float64)

print(tensor1.dtype)
print(tensor2.dtype)

torch.float64
torch.float64


In [12]:
# half (float16) 类型
tensor1 = torch.HalfTensor(2, 3)
tensor2 = torch.tensor([2, 3], dtype=torch.half)

print(tensor1.dtype)
print(tensor2.dtype)

torch.float16
torch.float16


In [13]:
# bool 类型
tensor1 = torch.BoolTensor(2, 3)
tensor2 = torch.tensor([2, 3], dtype=torch.bool)

print(tensor1.dtype)
print(tensor2.dtype)

torch.bool
torch.bool


4) 指定区间的张量创建

In [14]:
tensor1 = torch.arange(10, 30, 2)
print(tensor1)

tensor2 = torch.arange(6)
print(tensor2)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])
tensor([0, 1, 2, 3, 4, 5])


In [15]:
# 在指定区间内按元素数量创建张量
tensor1 = torch.linspace(10, 30, 6)
print(tensor1)

tensor([10., 14., 18., 22., 26., 30.])


In [18]:
# torch.logspace(start, end, steps, base) 在区间[start,end]之间生成steps个数，并以base为底，区间内的数为指数创建张量
tensor1 = torch.logspace(1, 3, 3, base=2)
print(tensor1)

tensor([2., 4., 8.])


5) 按数值填充张量

In [19]:
# torch.zeros(size) 创建指定形状的全0张量
tensor1 = torch.zeros(2, 3)
print(tensor1)

# torch.ones_like(input) 创建与给定张量形状相同的全1张量
tensor2 = torch.ones_like(tensor1)
print(tensor2)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [20]:
# torch.full(size,fill_value) 创建指定形状的按指定值填充的张量
tensor1 = torch.full((2, 3), 6)
print(tensor1)

# torch.empty_like(input) 创建与给定张量形状相同的未初始化的张量
tensor2 = torch.empty_like(tensor3)
print(tensor2)

tensor([[6, 6, 6],
        [6, 6, 6]])
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [21]:
# torch.eye(n) 创建n*n的单位矩阵
tensor1 = torch.eye(3)
print(tensor1)

# torch.eye(n, m) 按指定的行和列创建
tensor2 = torch.eye(3, 4)
print(tensor2)


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])


随机张量创建

In [22]:
# torch.rand(size) 创建在[0,1)上均匀分布的，指定形状的张量
tensor1 = torch.rand(2, 3)
print(tensor1)

# torch.rand_like(input) 创建在[0,1)上均匀分布的，与给定张量形状相同的张量
tensor2 = torch.randint_like(tensor1, 1, 10)
print(tensor2)

tensor([[0.9146, 0.8281, 0.9809],
        [0.6917, 0.9425, 0.3509]])
tensor([[6., 2., 1.],
        [6., 7., 3.]])


In [23]:
# torch.randn(size) 创建标准正态分布的，指定形状的张量
tensor1 = torch.randn(4, 2)
print(tensor1)

# torch.normal(mean,std,size) 创建自定义正态分布的，指定形状的张量。mean为均值，std为标准差
tensor2 = torch.normal(5, 1, tensor1.shape)
print(tensor2)

tensor([[-0.9618,  1.6451],
        [-1.1191, -0.3741],
        [-0.4364, -0.3898],
        [ 0.8453,  0.8152]])
tensor([[4.4724, 6.1675],
        [8.5134, 5.1854],
        [4.0878, 8.1359],
        [7.0786, 4.5531]])


In [24]:
# torch.randperm(n) 生成从0到n-1的随机排列（类似洗牌，随机重新排列）
tensor1 = torch.randperm(10)
print(tensor1)

tensor([5, 8, 1, 4, 6, 0, 3, 7, 2, 9])


In [25]:
# 查看随机数种子
print(torch.random.initial_seed())
# 设置随机数种子
torch.manual_seed(42)
print(torch.random.initial_seed())

22789536592100
42
