In [7]:
import torch

In [8]:
tensor1 = torch.randint(1, 10, (3, 2, 4)).float()
print(tensor1)

tensor([[[9., 2., 3., 5.],
         [5., 9., 8., 8.]],

        [[2., 6., 2., 8.],
         [9., 3., 1., 1.]],

        [[9., 2., 1., 4.],
         [6., 4., 8., 5.]]])


In [9]:
# sum 求和
print(tensor1.sum()) # 所有数求总和

tensor(120.)


In [10]:
print(tensor1.sum(dim=2))  # 将指定维度消去，聚合求和

tensor([[19., 30.],
        [18., 14.],
        [16., 23.]])


In [11]:
# mean 求均值
print(tensor1.mean())

tensor(5.)


In [12]:
print(tensor1.mean(dim=2))

tensor([[4.7500, 7.5000],
        [4.5000, 3.5000],
        [4.0000, 5.7500]])


In [13]:
# std 求标准方差
print(tensor1.std())

tensor(2.9192)


In [14]:
# max、min 求最大最小值
print(tensor1.max())

tensor(9.)


In [15]:
print(tensor1.min(dim=2))  # 得到两个元组，values 是指定维度值的最小值，indices 是最小值的索引

torch.return_types.min(
values=tensor([[2., 5.],
        [2., 1.],
        [1., 4.]]),
indices=tensor([[1, 0],
        [0, 2],
        [2, 1]]))


In [16]:
# 直接获取最大、最小值的索引
print(tensor1.argmin(dim=2))

tensor([[1, 0],
        [0, 2],
        [2, 1]])


In [17]:
print(tensor1.argmin()) # 向量化展开获取最小索引

tensor(14)


In [18]:
# unique 去重
print(tensor1.unique())  # 展开为一维张量并去重

tensor([1., 2., 3., 4., 5., 6., 8., 9.])


In [19]:
# 排序
print(tensor1.sort()) # 默认按最后一个维度排序

torch.return_types.sort(
values=tensor([[[2., 3., 5., 9.],
         [5., 8., 8., 9.]],

        [[2., 2., 6., 8.],
         [1., 1., 3., 9.]],

        [[1., 2., 4., 9.],
         [4., 5., 6., 8.]]]),
indices=tensor([[[1, 2, 3, 0],
         [0, 2, 3, 1]],

        [[0, 2, 1, 3],
         [2, 3, 1, 0]],

        [[2, 1, 3, 0],
         [1, 3, 0, 2]]]))
