In [50]:
import torch

In [51]:
tensor1 = torch.randint(1, 10, (3, 5, 4))
print(tensor1)

tensor([[[3, 2, 3, 1],
         [9, 7, 4, 1],
         [1, 4, 7, 2],
         [5, 9, 2, 1],
         [7, 2, 6, 2]],

        [[9, 4, 4, 5],
         [2, 9, 3, 3],
         [1, 7, 9, 4],
         [2, 2, 6, 4],
         [3, 5, 7, 4]],

        [[8, 5, 9, 2],
         [9, 5, 9, 1],
         [7, 4, 5, 1],
         [4, 1, 4, 6],
         [2, 9, 1, 9]]])


In [52]:
# 1. 简单索引
print(tensor1[2, 1, 3])

tensor(1)


In [53]:
print(tensor1[2, 3])

tensor([4, 1, 4, 6])


In [54]:
print(tensor1[1])

tensor([[9, 4, 4, 5],
        [2, 9, 3, 3],
        [1, 7, 9, 4],
        [2, 2, 6, 4],
        [3, 5, 7, 4]])


In [55]:
print(tensor1[:, 3])  # 所有矩阵第3行

tensor([[5, 9, 2, 1],
        [2, 2, 6, 4],
        [4, 1, 4, 6]])


In [56]:
# 2. 范围索引
print(tensor1[1:])  # 输出后两个矩阵

tensor([[[9, 4, 4, 5],
         [2, 9, 3, 3],
         [1, 7, 9, 4],
         [2, 2, 6, 4],
         [3, 5, 7, 4]],

        [[8, 5, 9, 2],
         [9, 5, 9, 1],
         [7, 4, 5, 1],
         [4, 1, 4, 6],
         [2, 9, 1, 9]]])


In [57]:
print(tensor1[-1, 1:4, 0:3])

tensor([[9, 5, 9],
        [7, 4, 5],
        [4, 1, 4]])


In [58]:
print(tensor1[-1, 1:4:2, 0:3:2])

tensor([[9, 9],
        [4, 4]])


In [59]:
# 列表索引
print(tensor1[
          [0, 1],
          [3, 2]])  # 每个维度的索引构成一个列表

tensor([[5, 9, 2, 1],
        [1, 7, 9, 4]])


In [60]:
print(tensor1[
          [0, 1],
          [3, 2],
          [2, 3]])  # 每个维度的索引构成一个列表
# [第 0 维 = 0，第1维 = 3，第2维=2, 第 0 维 = 1，第1维 = 2，第2维=3]

tensor([2, 4])


In [61]:
print(tensor1[
          [[0], [1]],
          [[1, 2]]])

# 2 * 2 * 4
# [[[第0维=0 第1维=1],
# [第0维=0 第1维=2]],
# [[第0维=1 第1维=1],
# [第0维=1 第1维=2]]]

tensor([[[9, 7, 4, 1],
         [1, 4, 7, 2]],

        [[2, 9, 3, 3],
         [1, 7, 9, 4]]])


In [62]:
# 布尔索引
# 选取符合条件的行，首元素大于5
mask = tensor1[:, :, 0] > 5
print(mask)  # 3 * 5

tensor([[False,  True, False, False,  True],
        [ True, False, False, False, False],
        [ True,  True,  True, False, False]])


In [63]:
print(tensor1[mask])  # 过滤出符合条件的数据

tensor([[9, 7, 4, 1],
        [7, 2, 6, 2],
        [9, 4, 4, 5],
        [8, 5, 9, 2],
        [9, 5, 9, 1],
        [7, 4, 5, 1]])


In [64]:
# 选取符合条件的列，第二个元素大于5
mask = tensor1[:, 1, :] > 5
print(mask)  # 3 * 4

tensor([[ True,  True, False, False],
        [False,  True, False, False],
        [ True, False,  True, False]])


In [65]:
tensor2 = tensor1.mT  # mT 是对矩阵转置，直接用 T 是把 3 * 5 * 4 转变为 4*5*3
print(tensor2)

tensor([[[3, 9, 1, 5, 7],
         [2, 7, 4, 9, 2],
         [3, 4, 7, 2, 6],
         [1, 1, 2, 1, 2]],

        [[9, 2, 1, 2, 3],
         [4, 9, 7, 2, 5],
         [4, 3, 9, 6, 7],
         [5, 3, 4, 4, 4]],

        [[8, 9, 7, 4, 2],
         [5, 5, 4, 1, 9],
         [9, 9, 5, 4, 1],
         [2, 1, 1, 6, 9]]])


In [66]:
print(tensor2[mask].mT)

tensor([[3, 2, 4, 8, 9],
        [9, 7, 9, 9, 9],
        [1, 4, 7, 7, 5],
        [5, 9, 2, 4, 4],
        [7, 2, 5, 2, 1]])


In [67]:
# 选取符合条件的矩阵
# 元素 (1,2) >5
mask = tensor1[:, 1, 2] > 5
print(mask)

tensor([False, False,  True])


In [68]:
print(tensor1[mask])

tensor([[[8, 5, 9, 2],
         [9, 5, 9, 1],
         [7, 4, 5, 1],
         [4, 1, 4, 6],
         [2, 9, 1, 9]]])
