In [1]:
import torch

In [2]:
tensor1 = torch.randint(1, 10, (2, 3, 6))
print(tensor1)

tensor([[[2, 5, 8, 5, 7, 1],
         [2, 6, 8, 1, 2, 4],
         [5, 4, 4, 3, 4, 4]],

        [[2, 2, 6, 1, 2, 3],
         [5, 9, 1, 3, 2, 1],
         [3, 5, 5, 3, 1, 2]]])


交换维度

In [3]:
# 交换两个维度
print(tensor1.transpose(1, 2))  # 第 1 维和 第 2 维 交换

tensor([[[2, 2, 5],
         [5, 6, 4],
         [8, 8, 4],
         [5, 1, 3],
         [7, 2, 4],
         [1, 4, 4]],

        [[2, 5, 3],
         [2, 9, 5],
         [6, 1, 5],
         [1, 3, 3],
         [2, 2, 1],
         [3, 1, 2]]])


In [4]:
# 重新排列多个维度
print(tensor1.permute(0, 2, 1))

tensor([[[2, 2, 5],
         [5, 6, 4],
         [8, 8, 4],
         [5, 1, 3],
         [7, 2, 4],
         [1, 4, 4]],

        [[2, 5, 3],
         [2, 9, 5],
         [6, 1, 5],
         [1, 3, 3],
         [2, 2, 1],
         [3, 1, 2]]])


调整形状

In [5]:
# 1.reshape
tensor1 = torch.randint(1, 10, (3, 5, 4))
print(tensor1.shape)

torch.Size([3, 5, 4])


In [6]:
print(tensor1.reshape(6, 10))  # 相乘的总元素个数要和原始张量的总元素个数相同

tensor([[4, 2, 5, 7, 7, 9, 6, 7, 9, 8],
        [2, 6, 1, 2, 7, 8, 9, 1, 2, 7],
        [4, 6, 3, 3, 9, 2, 5, 8, 1, 4],
        [5, 4, 8, 5, 1, 6, 8, 1, 5, 8],
        [9, 8, 3, 3, 7, 9, 4, 1, 4, 7],
        [6, 4, 3, 9, 4, 5, 1, 5, 3, 4]])


In [7]:
print(tensor1.reshape(3, -1))  # 第二个参数自动计算

tensor([[4, 2, 5, 7, 7, 9, 6, 7, 9, 8, 2, 6, 1, 2, 7, 8, 9, 1, 2, 7],
        [4, 6, 3, 3, 9, 2, 5, 8, 1, 4, 5, 4, 8, 5, 1, 6, 8, 1, 5, 8],
        [9, 8, 3, 3, 7, 9, 4, 1, 4, 7, 6, 4, 3, 9, 4, 5, 1, 5, 3, 4]])


In [8]:
print(tensor1.reshape(-1))  # 行向量化

tensor([4, 2, 5, 7, 7, 9, 6, 7, 9, 8, 2, 6, 1, 2, 7, 8, 9, 1, 2, 7, 4, 6, 3, 3,
        9, 2, 5, 8, 1, 4, 5, 4, 8, 5, 1, 6, 8, 1, 5, 8, 9, 8, 3, 3, 7, 9, 4, 1,
        4, 7, 6, 4, 3, 9, 4, 5, 1, 5, 3, 4])


In [9]:
# 2. 用 view 调整
print(tensor1.is_contiguous())  # view 只能在连续的内存空间上使用，所以要判断是否内存空间上连续

True


In [10]:
print(tensor1.view(-1, 10))

tensor([[4, 2, 5, 7, 7, 9, 6, 7, 9, 8],
        [2, 6, 1, 2, 7, 8, 9, 1, 2, 7],
        [4, 6, 3, 3, 9, 2, 5, 8, 1, 4],
        [5, 4, 8, 5, 1, 6, 8, 1, 5, 8],
        [9, 8, 3, 3, 7, 9, 4, 1, 4, 7],
        [6, 4, 3, 9, 4, 5, 1, 5, 3, 4]])


In [11]:
print(tensor1.shape)

torch.Size([3, 5, 4])


In [12]:
# 对张量进行转置操作，让内存空间不连续
tensor1 = tensor1.permute(2, 1, 0)
print(tensor1.shape)
print(tensor1.is_contiguous())

torch.Size([4, 5, 3])
False


In [13]:
print(tensor1.contiguous().view(-1, 10))  # 强制内存连续后才能用 view 调整

tensor([[4, 4, 9, 7, 9, 7, 9, 1, 4, 1],
        [8, 3, 9, 8, 1, 2, 6, 8, 9, 2],
        [9, 8, 4, 7, 2, 5, 9, 1, 1, 5],
        [5, 3, 3, 6, 5, 4, 2, 5, 6, 7],
        [1, 4, 2, 5, 3, 7, 3, 3, 7, 8],
        [1, 6, 4, 4, 8, 6, 5, 7, 8, 4]])


增加或删除维度

In [14]:
tensor1 = torch.tensor([1, 2, 3])
print(tensor1)

tensor([1, 2, 3])


In [15]:
# 在 0 维上增加一个维度, 1*3
print(tensor1.unsqueeze(dim=0))

tensor([[1, 2, 3]])


In [16]:
# 在 1 维上增加一个维度, 3*1
print(tensor1.unsqueeze(dim=1))
print(tensor1)

tensor([[1],
        [2],
        [3]])
tensor([1, 2, 3])


In [17]:
# 在-2维上增加一个维度, 原地操作
print(tensor1.unsqueeze_(dim=-2))
print(tensor1)

tensor([[1, 2, 3]])
tensor([[1, 2, 3]])


In [18]:
# 减少维度
print(tensor1.squeeze(dim=0))

tensor([1, 2, 3])


张量拼接操作

In [19]:
# 拼接
tensor1 = torch.randint(1, 10, (2, 2, 5))  # 2 * 2 * 5
tensor2 = torch.randint(1, 10, (2, 3, 5))  # 2 * 3 * 5
print(tensor1)
print(tensor2)

tensor([[[6, 1, 9, 5, 9],
         [9, 4, 6, 4, 5]],

        [[4, 5, 2, 7, 6],
         [2, 5, 5, 5, 1]]])
tensor([[[6, 3, 6, 6, 8],
         [5, 2, 2, 5, 6],
         [1, 8, 7, 5, 3]],

        [[7, 3, 9, 8, 8],
         [1, 1, 2, 8, 3],
         [2, 5, 5, 6, 2]]])


In [20]:
# cat 拼接
# 按已有维度拼接。除拼接维度外，其他维度大小须相同
print(torch.cat((tensor1, tensor2), dim=1))  # 2 * 5 * 5

tensor([[[6, 1, 9, 5, 9],
         [9, 4, 6, 4, 5],
         [6, 3, 6, 6, 8],
         [5, 2, 2, 5, 6],
         [1, 8, 7, 5, 3]],

        [[4, 5, 2, 7, 6],
         [2, 5, 5, 5, 1],
         [7, 3, 9, 8, 8],
         [1, 1, 2, 8, 3],
         [2, 5, 5, 6, 2]]])


In [21]:
# stack 张量堆叠，按新维度堆叠。所有张量形状必须一致。可以都放到 dim = 0，然后再调形状
tensor1 = torch.randint(1, 10, (4, 3, 5))  # 4 * 2 * 5
tensor2 = torch.randint(1, 10, (4, 3, 5))  # 4 * 3 * 5
print(tensor1)
print(tensor2)

tensor([[[5, 2, 4, 1, 9],
         [7, 2, 3, 6, 8],
         [6, 1, 7, 6, 3]],

        [[4, 7, 7, 9, 1],
         [8, 8, 5, 5, 9],
         [6, 8, 3, 6, 2]],

        [[5, 4, 1, 6, 4],
         [5, 5, 7, 4, 6],
         [7, 6, 3, 9, 1]],

        [[9, 7, 8, 1, 9],
         [8, 7, 7, 1, 4],
         [4, 7, 6, 5, 1]]])
tensor([[[7, 9, 8, 9, 5],
         [4, 3, 4, 7, 4],
         [2, 5, 9, 9, 9]],

        [[9, 1, 9, 1, 5],
         [9, 7, 6, 6, 7],
         [7, 5, 8, 6, 3]],

        [[4, 2, 6, 4, 6],
         [6, 8, 2, 5, 4],
         [2, 4, 7, 4, 5]],

        [[2, 5, 3, 4, 8],
         [7, 4, 4, 1, 8],
         [2, 2, 5, 8, 9]]])


In [23]:
tensor3 = torch.stack([tensor1, tensor2], dim=0)
print(tensor3)
print(tensor3.shape)

tensor([[[[5, 2, 4, 1, 9],
          [7, 2, 3, 6, 8],
          [6, 1, 7, 6, 3]],

         [[4, 7, 7, 9, 1],
          [8, 8, 5, 5, 9],
          [6, 8, 3, 6, 2]],

         [[5, 4, 1, 6, 4],
          [5, 5, 7, 4, 6],
          [7, 6, 3, 9, 1]],

         [[9, 7, 8, 1, 9],
          [8, 7, 7, 1, 4],
          [4, 7, 6, 5, 1]]],


        [[[7, 9, 8, 9, 5],
          [4, 3, 4, 7, 4],
          [2, 5, 9, 9, 9]],

         [[9, 1, 9, 1, 5],
          [9, 7, 6, 6, 7],
          [7, 5, 8, 6, 3]],

         [[4, 2, 6, 4, 6],
          [6, 8, 2, 5, 4],
          [2, 4, 7, 4, 5]],

         [[2, 5, 3, 4, 8],
          [7, 4, 4, 1, 8],
          [2, 2, 5, 8, 9]]]])
torch.Size([2, 4, 3, 5])


In [24]:
tensor3 = torch.stack([tensor1, tensor2], dim=1) # 增加的维度放到第一维
print(tensor3.shape)

tensor([[[[5, 2, 4, 1, 9],
          [7, 2, 3, 6, 8],
          [6, 1, 7, 6, 3]],

         [[7, 9, 8, 9, 5],
          [4, 3, 4, 7, 4],
          [2, 5, 9, 9, 9]]],


        [[[4, 7, 7, 9, 1],
          [8, 8, 5, 5, 9],
          [6, 8, 3, 6, 2]],

         [[9, 1, 9, 1, 5],
          [9, 7, 6, 6, 7],
          [7, 5, 8, 6, 3]]],


        [[[5, 4, 1, 6, 4],
          [5, 5, 7, 4, 6],
          [7, 6, 3, 9, 1]],

         [[4, 2, 6, 4, 6],
          [6, 8, 2, 5, 4],
          [2, 4, 7, 4, 5]]],


        [[[9, 7, 8, 1, 9],
          [8, 7, 7, 1, 4],
          [4, 7, 6, 5, 1]],

         [[2, 5, 3, 4, 8],
          [7, 4, 4, 1, 8],
          [2, 2, 5, 8, 9]]]])
torch.Size([4, 2, 3, 5])
