In [12]:
import torch

In [13]:
x = torch.tensor(2.0, requires_grad=True)
y = x.detach()

In [14]:
print(x.requires_grad)
print(y.requires_grad)  # False

True
False


In [15]:
# 分离后不是同一个对象
print(id(x))
print(id(y))

1606634590432
1606634590912


In [16]:
# 底层数据存储是共享的
print(x.untyped_storage().data_ptr())
print(y.untyped_storage().data_ptr())

6318568047296
6318568047296


In [17]:
z1 = x ** 2
z2 = y ** 2
print(z1)
print(z2)

tensor(4., grad_fn=<PowBackward0>)
tensor(4.)


In [18]:
z1.sum().backward()
# z2.sum().backward() # 没有启用梯度计算，调用会报错

In [19]:
x = torch.ones(2, 2, requires_grad=True)
y = x * x
print(x)
print(y)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


In [20]:
u = y.detach()
print(u)

tensor([[1., 1.],
        [1., 1.]])


In [21]:
# 让 u 参与新张量的运算
z = u * x

# 反向传播，计算所有梯度
z.sum().backward()
print(x.grad)

print(x.grad == u)

tensor([[1., 1.],
        [1., 1.]])
tensor([[True, True],
        [True, True]])
