# ndarray
NumPy 中的 ndarray 是一个多维数组对象，它是 NumPy 的核心数据结构。ndarray 可以存储同类型的数据，并且支持多维数组操作。

## 1.ndarray 的特性
### 多维

In [133]:
import numpy as np

In [134]:
arr = np.array(5) # 0 维数组
print(arr)
print('维度:', arr.ndim) # 数组的维度

5
维度: 0


In [135]:
arr = np.array([1,2,3]) # 1 维数组
print(arr)
print('维度:', arr.ndim) # 数组的维度

[1 2 3]
维度: 1


In [136]:
arr = np.array([[1,2,3],[4,5,6]]) # 2 维数组
print(arr)
print('维度:', arr.ndim) # 数组的维度

[[1 2 3]
 [4 5 6]]
维度: 2


### 同质

In [137]:
arr = np.array([1,'hello']) # 不同类型的数据会被转化成同一类型
print(arr)

['1' 'hello']


In [138]:
arr = np.array([[1,2,3],[4,5,6]], dtype=np.float32) # 指定数据类型
print(arr)
print('数据类型:', arr.dtype) # 数组的数据类型被转化成指定类型

[[1. 2. 3.]
 [4. 5. 6.]]
数据类型: float32


## 2.ndarray 的属性

## 属性

| 属性名称     | 描述                         | 使用示例         |
|----------|----------------------------|--------------|
| shape    | 数组的形状：各个维度的尺寸              | arr.shape    |
| ndim     | 维度数量                       | arr.ndim     |
| size     | 总元素个数                      | arr.size     |
| dtype    | 数据类型                       | arr.dtype    |
| T        | 转置数组                       | arr.T        |
| itemsize | 每个元素的字节大小                  | arr.itemsize |
| nbytes   | 数组的总字节大小 (size * itemsize) | arr.nbytes   |
| flags    | 数组的内存布局标志                  | arr.flags    |


In [139]:
# 零维数组
arr = np.array(1)
print(arr)
print('shape:', arr.shape)  # 数组的形状
print('ndim:', arr.ndim)    # 数组的维度
print('size:', arr.size)    # 数组的元素个数
print('dtype:', arr.dtype)  # 数组的数据类型
print('T:', arr.T)        # 转置数组（零维数组转置仍为自身）

1
shape: ()
ndim: 0
size: 1
dtype: int64
T: 1


In [140]:
# 一维数组
arr = np.array([1, 2, 3])
print(arr)
print('shape:', arr.shape)  # 数组的形状
print('ndim:', arr.ndim)    # 数组的维度
print('size:', arr.size)    # 数组的元素个数
print('dtype:', arr.dtype)  # 数组的数据类型
print('T:', arr.T)        # 转置数组（一维数组转置仍为自身）

[1 2 3]
shape: (3,)
ndim: 1
size: 3
dtype: int64
T: [1 2 3]


In [141]:
# 二维行向量
arr = np.array([[1, 2, 3]])
print(arr)
print('shape:', arr.shape)  # 数组的形状
print('ndim:', arr.ndim)    # 数组的维度
print('size:', arr.size)    # 数组的元素个数
print('dtype:', arr.dtype)  # 数组的数据类型
print('T:', arr.T)        # 转置数组（二维行向量转置为列向量）

[[1 2 3]]
shape: (1, 3)
ndim: 2
size: 3
dtype: int64
T: [[1]
 [2]
 [3]]


In [142]:
# 二维列向量
arr = np.array([[1], [2.5], [3]])
print(arr)
print('shape:', arr.shape)  # 数组的形状
print('ndim:', arr.ndim)    # 数组的维度
print('size:', arr.size)    # 数组的元素个数
print('dtype:', arr.dtype)  # 数组的数据类型
print('T:', arr.T)        # 转置数组（二维列向量转置为行向量）

[[1. ]
 [2.5]
 [3. ]]
shape: (3, 1)
ndim: 2
size: 3
dtype: float64
T: [[1.  2.5 3. ]]


In [143]:
# 二维数组
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('shape:', arr.shape)  # 数组的形状
print('ndim:', arr.ndim)    # 数组的维度
print('size:', arr.size)    # 数组的元素个数
print('dtype:', arr.dtype)  # 数组的数据类型
print('T:', arr.T)        # 转置数组（二维数组转置）

[[1 2 3]
 [4 5 6]]
shape: (2, 3)
ndim: 2
size: 6
dtype: int64
T: [[1 4]
 [2 5]
 [3 6]]
