# ndarray 的创建

In [279]:
import numpy as np
list1 = [1, 2, 3, 4, 5]
# 通过列表创建 ndarray
array1 = np.array(list1)
print(array1)
print(array1.ndim)  # 输出数组的维度

# 通过元组创建 ndarray
tuple1 = (6, 7, 8, 9, 10)
array2 = np.array(tuple1)
print(array2)
print(array2.ndim)  # 输出数组的维度

[1 2 3 4 5]
1
[ 6  7  8  9 10]
1


In [280]:
# copy 和 view
array3 = array1.copy()  # 创建一个新的 ndarray
print('arr3:',array3)
array4 = array1.view()  # 创建一个视图
print('arr4:',array4)

# 修改原数组
array1[0] = 100
print('原数组',array1)  # 原数组
print('copy 的数组:',array3)  # copy 的数组不受影响
print('view 的数组:',array4)  # view 的数组会受影响

arr3: [1 2 3 4 5]
arr4: [1 2 3 4 5]
原数组 [100   2   3   4   5]
copy 的数组: [1 2 3 4 5]
view 的数组: [100   2   3   4   5]


In [281]:
# 预定义形状
# 创建一个全为 0 的 ndarray
array_zeros = np.zeros((2, 3),dtype=int)  # 2行3列
array_zeros_1 = np.zeros((3,),dtype=int)  # 一维
print(array_zeros)
print('array_zeros_1:',array_zeros_1)

# 输出数据类型默认为 float64,可以通过 dtype 参数指定为 int
print('类型:',array_zeros.dtype) 

[[0 0 0]
 [0 0 0]]
array_zeros_1: [0 0 0]
类型: int64


In [282]:
# 创建一个全为 1 的 ndarray
array_ones = np.ones((2, 3), dtype=int)  # 2行3列
array_ones_1 = np.ones((3,), dtype=int)  # 一维
print(array_ones)
print(array_ones_1)

[[1 1 1]
 [1 1 1]]
[1 1 1]


In [283]:
# 未初始化
# 创建一个未初始化的 ndarray
array_empty = np.empty((4, 3), dtype=int)  # 4行3列
array_empty_1 = np.empty((3,), dtype=int)  # 一维
print(array_empty)
print(array_empty_1)

[[      3123847026568                  64                   0]
 [                  0 8751735922824839168 7077745675407353187]
 [4051094751023685938 7017280447209287777 4134975379924463973]
 [4063989822605255782 3991657535397573730 4063145586623329124]]
[1 1 1]


In [284]:
# 指定值
# 创建一个全为指定值的 ndarray
array_full = np.full((2, 3), 7, dtype=int)  # 2行3列
print(array_full)

# 创建一个形如 array_full 的全 0 ndarray
array_zeros_like = np.zeros_like(array_full)  # 2行3列
print(array_zeros_like)

# 创建一个形如 array_full 的全 1 ndarray
array_ones_like = np.ones_like(array_full)  # 2行3列
print(array_ones_like)

# 同理还有 empty_like 和 full_like

[[7 7 7]
 [7 7 7]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


In [294]:
# 创建一个单位矩阵
array_eye = np.eye(3, dtype=np.int64)  # 3x3单位矩阵
print(array_eye)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [286]:
# 创建一个对角矩阵
array_diag = np.diag([1, 2, 3, 4])  # 对角线为 [1, 2, 3, 4] 的矩阵
print(array_diag)
# 创建一个对角矩阵，指定对角线位置
array_diag_k = np.diag([1, 2, 3, 4], k=1)  # 上对角线
print(array_diag_k)
# 创建一个对角矩阵，指定对角线位置
array_diag_m = np.diag([1, 2, 3, 4], k=-1)  # 下对角线
print(array_diag_m)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [287]:
# 创建一个等差数列
array_arange = np.arange(0, 10, 2)  # 从 0 到 10，步长为 2 (0,2,4,6,8)
print(array_arange)

[0 2 4 6 8]


In [288]:
# 等间隔数列
array_linspace = np.linspace(0, 1, 5)  # 从 0 到 1，包含 5 个点
print(array_linspace)

[0.   0.25 0.5  0.75 1.  ]


In [289]:
# 对数间隔数列
array_logspace = np.logspace(0, 2, 5)  # 从 10^0 到 10^2，包含 5 个点（默认底数是 10）
print(array_logspace)

# 创建一个对数间隔数列，指定底数
array_logspace_base = np.logspace(0, 2, 5, base=2)  # 从 2^0 到 2^2，包含 5 个点，底数为 2

[  1.           3.16227766  10.          31.6227766  100.        ]


In [290]:
# 创建一个随机数数组
array_random = np.random.rand(3, 2)  # 3行2列的随机数数组（ 0 到 1 之间均匀分布）
print(array_random)

[[0.21767187 0.49347546]
 [0.03014642 0.11643775]
 [0.1727809  0.06719469]]


In [291]:
# 生成指定范围内的随机浮点数
array_random_uniform = np.random.uniform(1, 10, (3, 2))  # 3行2列的随机数数组（1到10之间均匀分布）
print(array_random_uniform)

[[3.57754673 7.13006268]
 [6.878171   5.26289505]
 [2.55422017 4.2538671 ]]


In [292]:
# 生成指定范围内的随机整数
array_random_integers = np.random.randint(1, 10, (3, 2))  # 3行2列的随机整数数组（1到10之间）
print(array_random_integers)

[[8 9]
 [5 3]
 [9 5]]


In [293]:
# 生成正态分布的随机数
# 标准正态分布（均值为 0，标准差为 1）
standard_normal = np.random.randn(3, 2)  # 3行2列的标准正态分布随机数
print(standard_normal)

# 生成指定均值和标准差的正态分布随机数(更常用)
array_random_normal = np.random.normal(0, 1, (3, 2))  # 均值为 0，标准差为 1 的正态分布随机数
print(array_random_normal)

[[-0.49297348  2.35022786]
 [ 1.25192044  2.32481316]
 [ 1.32865662  1.73803669]]
[[ 0.24445663  1.40235167]
 [-0.0557758   1.5968471 ]
 [-1.3298     -0.84078247]]
