# ndarray的索引和切片

NumPy数组的索引和切片与Python的列表类似，但有一些重要的区别。NumPy数组支持多维索引和切片，这使得它们在处理多维数据时非常强大。

In [70]:
# 一维数组的索引和切片
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("一维数组:", arr)

# 索引
print("索引 0 ", arr[0])  # 输出第一个元素
print("索引 2 ", arr[2])  # 输出第三个元素
# 布尔索引
print("布尔索引 arr > 2 ", arr[arr > 2])  # 输出大于2的元素
print("布尔索引 arr >2 且 arr < 5 ", arr[(arr > 2) & (arr < 5)])  # 输出大于2且小于5的元素

# 切片(左闭右开区间) 
print("切片 1:3 ", arr[1:3])  # 输出第二到第三个元素
# 负索引
print("负索引 -1 ", arr[-1])  # 输出最后一个元素
# 负切片
print("负切片 -3:-1 ", arr[-3:-1])  # 输出倒数第三到倒数第二个元素
# 切片到末尾
print("切片 2: ", arr[2:])  # 输出从第三个元素到最后一个元素
# 切片到开头
print("切片 :3 ", arr[:3])  # 输出前三个元素
# 全部切片
print("全部切片 :", arr[:])  # 输出所有元素
# 步长切片
print("步长切片 1:5:2 ", arr[1:5:2])  # 输出从第二个到第五个元素，步长为2

一维数组: [1 2 3 4 5]
索引 0  1
索引 2  3
布尔索引 arr > 2  [3 4 5]
布尔索引 arr >2 且 arr < 5  [3 4]
切片 1:3  [2 3]
负索引 -1  5
负切片 -3:-1  [3 4]
切片 2:  [3 4 5]
切片 :3  [1 2 3]
全部切片 : [1 2 3 4 5]
步长切片 1:5:2  [2 4]


In [71]:
# 二维数组的索引和切片
arr2d = np.array([[1, 2, 3,4], [4, 5, 6,7], [7, 8, 9,10]])
print("\n二维数组:\n", arr2d)

# 索引
print("第一行第第二列:", arr2d[0, 1])  # 输出第一行第二列的元素
print("第三行第三列:", arr2d[2, 2])  # 输出第三行第三列的元素

print("第二行:",arr2d[1])  # 输出第二行
print("第二列",arr2d[:, 1])  # 输出第二列
print("第二行从第三列到最后一列:",arr2d[1, 2:])  # 输出第二行从第三列到最后一列的元素


二维数组:
 [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
第一行第第二列: 2
第三行第三列: 9
第二行: [4 5 6 7]
第二列 [2 5 8]
第二行从第三列到最后一列: [6 7]


In [72]:
# 二维数组布尔索引
print("\n二维数组布尔索引:")
print("大于5的元素:\n", arr2d[arr2d > 5])  # 输出大于5的元素 (会以一维数组形式输出)

print("大于5的元素所在位置:\n", np.argwhere(arr2d > 5))  # 输出大于5的元素所在位置

print("大于5的元素所在行:\n", arr2d[np.any(arr2d > 5, axis=1)])  # 输出大于5的元素所在行

print("大于8的元素所在列:\n", arr2d[:, np.any(arr2d > 8, axis=0)])  # 输出大于5的元素所在列

print("大于5的元素所在行和列:\n", arr2d[np.any(arr2d > 5, axis=1), :][:, np.any(arr2d > 5, axis=0)])  # 输出大于5的元素所在行和列

print("第一行和第二行的元素大于5:\n", arr2d[:2, :][arr2d[:2, :] > 5])  # 输出第一行和第二行的元素大于5的元素


二维数组布尔索引:
大于5的元素:
 [ 6  7  7  8  9 10]
大于5的元素所在位置:
 [[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]]
大于5的元素所在行:
 [[ 4  5  6  7]
 [ 7  8  9 10]]
大于8的元素所在列:
 [[ 3  4]
 [ 6  7]
 [ 9 10]]
大于5的元素所在行和列:
 [[ 4  5  6  7]
 [ 7  8  9 10]]
第一行和第二行的元素大于5:
 [6 7]


> 注意：在NumPy中，切片操作返回的是原数组的视图，而不是副本。这意味着对切片的修改会影响原数组。
> 如果需要创建一个副本，可以使用`copy()`方法。
> 例如：
> ```python
> arr_slice = arr[1:3].copy()  # 创建一个切片的副本
> ```
> 如果对`arr_slice`进行修改，原数组`arr`不会受到影响。

## 区分 arr[:][3] 和 arr[:, 3]

在NumPy中，`arr[:][3]`和`arr[:, 3]`是不同的操作。

`arr[:][3]` 执行过程：
1. arr[:] 获取所有行
2. 从结果中获取第 3 行

等价于 arr[3]，最终返回的是数组的第四行（索引从0开始）。

`arr[:, 3]`则是直接对二维数组进行切片，获取所有行的第四列。
