# 5. numpy中常用函数

## 1. 数学函数

In [397]:
import numpy as np

# 计算平方根
print(np.sqrt([1, 4, 9, 16]))  # 1. 2. 3. 4.
print(np.sqrt(9))  # 3.0


[1. 2. 3. 4.]
3.0


In [398]:
# 计算立方根
print(np.cbrt([1, 8, 27, 64]))  # 1. 2. 3. 4.
print(np.cbrt(27))  # 3.0

[1. 2. 3. 4.]
3.0


In [399]:
# 计算指数
print(np.exp([1, 2, 3]))  # e^1, e^2, e^3

[ 2.71828183  7.3890561  20.08553692]


In [400]:
# 计算自然对数 lnX
print(np.log([1, np.e, np.e ** 2]))  # log(1), log(e), log(e^2)

[0. 1. 2.]


In [401]:
# 计算正弦、余弦、正切
print(np.sin(np.pi / 2))  # 1.0
print(np.cos(0))  # 1.0
print(np.tan(np.pi / 4))

1.0
1.0
0.9999999999999999


In [402]:
# 计算绝对值
print(np.abs([-1, -2, -3]))  # 1 2 3

[1 2 3]


In [403]:
# 计算 a 的 b 次幂
print(np.power([1, 2, 3], 2))  # 1 4 9

[1 4 9]


In [404]:
# 四舍六入偶成双
print(np.round([1.2, 2.5, 3.7]))  # 1.0 3.0 4.0

[1. 2. 4.]


In [405]:
# 向上取整，向下取整
print(np.ceil([1.2, 2.5, 3.7]))  # 2.0 3.0 4.0
print(np.floor([1.2, 2.5, 3.7]))  # 1.0 2.0 3.0

[2. 3. 4.]
[1. 2. 3.]


In [406]:
# 检测是否为NaN
print(np.isnan([1, np.nan, 3]))  # False True False

[False  True False]


# 2. 统计函数

In [407]:
arr = np.random.randint(1, 10, (3, 4))
print(arr)

[[4 1 9 1]
 [8 2 3 2]
 [9 4 3 1]]


In [408]:
# 求和
print(np.sum(arr))  # 所有元素之和

47


In [409]:
# 按轴求和
print(np.sum(arr, axis=0))  # 按列求和
print(np.sum(arr, axis=1))  # 按行求和

[21  7 15  4]
[15 15 17]


In [410]:
# 求均值
print(np.mean(arr))  # 所有元素的平均值

3.9166666666666665


In [411]:
# 按轴求均值
print(np.mean(arr, axis=0))  # 按列求均值
print(np.mean(arr, axis=1))  # 按行求均值

[7.         2.33333333 5.         1.33333333]
[3.75 3.75 4.25]


In [412]:
# 求中位数
print(np.median(arr))  # 所有元素的中位数

3.0


In [413]:
# 计算标准差、方差 (离散程度)
print(np.std([1, 2, 3]))  # 所有元素的标准差 ((1-2)^2 + (2-2)^2 + (3-2)^2) / 3 
print(np.var([1, 2, 3]))  # 所有元素的方差 上面的结果开根号

0.816496580927726
0.6666666666666666


In [414]:
# 计算最大值、最小值
print(np.max(arr), np.argmax(arr))  # 所有元素的最大值, 最大值的索引
print(np.min(arr), np.argmin(arr))  # 所有元素的最小值, 最小值的索引

9 2
1 1


In [415]:
# 分位数 
print(np.percentile(arr, 25))  # 25%分位数

1.75


In [416]:
# 计算累积和,累积积
print(np.cumsum([1, 2, 3, 4]))  # 1 3 6 10
print(np.cumprod([1, 2, 3, 4]))  # 1 2 6 24

[ 1  3  6 10]
[ 1  2  6 24]


# 3.比较函数

In [417]:
# 是否大于
print(np.greater([1, 2, 3], [0, 2, 1]))  # [ True False  True]
print(np.greater([1, 2, 3], 2))  # [False False  True]

# 是否小于
print(np.less([1, 2, 3], [0, 2, 1]))  # [False False False]
print(np.less([1, 2, 3], 2))  # [ True False False]

# 是否等于
print(np.equal([1, 2, 3], [0, 2, 1]))  # [False  True False]
# 是否不等于
print(np.not_equal([1, 2, 3], [0, 2, 1]))  # [ True False  True]

[ True False  True]
[False False  True]
[False False False]
[ True False False]
[False  True False]
[ True False  True]


In [418]:
# 逻辑与
print(np.logical_and([1, 0], [1, 1]))  # [ True False]
# 逻辑或
print(np.logical_or([1, 0], [1, 1]))  # [ True  True]
# 逻辑非
print(np.logical_not([1, 0]))  # [False  True]

[ True False]
[ True  True]
[False  True]


In [419]:
# 检查元素是否至少有一个为True
print(np.any([0, 1, 0]))  # True
# 检查元素是否全部为True
print(np.all([0, 1, 0]))  # False

True
False


In [420]:
# 自定义条件
def custom_condition(x):
    return x > 2


# 使用自定义条件
print(np.frompyfunc(custom_condition, 1, 1)([1, 2, 3, 4]))  # [False False True True]

print(np.where(np.array([1, 2, 3, 4]) > 2, '大于2', '小于等于2'))  # ['小于等于2' '小于等于2' '大于2' '大于2']

score = np.array([90, 80, 70, 60, 50, 40])
print(np.where(score >= 60, '及格', '不及格'))  # ['及格' '及格' '及格' '及格' '不及格' '不及格']

[False False True True]
['小于等于2' '小于等于2' '大于2' '大于2']
['及格' '及格' '及格' '及格' '不及格' '不及格']


In [422]:
print(np.where(
    score < 60, '不及格', np.where(
        score < 80, '良好','优秀'
    )
))

['优秀' '优秀' '良好' '良好' '不及格' '不及格']


In [423]:
# np.select(条件, 结果, default=默认值) 
print(np.select(
    [score < 60, score < 80],
    ['不及格', '良好'],
    default='优秀'
))  # ['不及格' '良好' '良好' '优秀' '优秀' '优秀']

['优秀' '优秀' '良好' '良好' '不及格' '不及格']


# 4. 排序函数

In [427]:
np.random.seed(0)
arr = np.random.randint(1, 100, (3, 4))
print(arr)
# arr.sort()  # 按行排序
print(np.argsort(arr))  # 返回排序后的索引
print(arr) 

[[45 48 65 68]
 [68 10 84 22]
 [37 88 71 89]]
[[0 1 2 3]
 [1 3 0 2]
 [0 2 1 3]]
[[45 48 65 68]
 [68 10 84 22]
 [37 88 71 89]]


In [425]:
# 按列排序
arr = np.random.randint(1, 100, (3, 4))
print(arr)
arr.sort(axis=0)  # 按列排序
print(arr) 

[[89 13 59 66]
 [40 88 47 89]
 [82 38 26 78]]
[[40 13 26 66]
 [82 38 47 78]
 [89 88 59 89]]


In [429]:
# 去重 and 排序
arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_arr = np.unique(arr)
print(unique_arr)  # [1 2 3 4 5]

[1 2 3 4 5]


In [430]:
# 数组的拼接 (一维的可以 使用 np.concatenate)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
# 按行拼接
arr_h = np.hstack((arr1, arr2))

print(arr_h)  # [[1 2 5 6] [3 4 7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# 按列拼接
arr_v = np.vstack((arr1, arr2))
print(arr_v)  # [[1 2] [3 4] [5 6] [7 8]]

In [432]:
# 调整数组形状
arr = np.arange(12)
print(arr)  # [0 1 2 3 4 5 6 7 8 9 10 11]
# 调整为2行6列
arr_reshaped = arr.reshape(2, 6) 
print(arr_reshaped)  # [[0 1 2 3 4 5] [6 7 8 9 10 11]]

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
