In [ ]:
import numpy as np

题目1：温度数据分析
某城市一周的温度数据：[28, 30, 32, 31, 29, 28, 27]。
- 请计算这周的平均温度、最高温度和最低温度
- 请找出温度超过30度的天数

In [1]:
# 温度数据
temperatures = np.array([28, 30, 32, 31, 29, 28, 27])
# 计算平均温度
average_temp = np.mean(temperatures)
print(f"平均温度: {average_temp:.2f}°C")
# 计算最高温度
max_temp = np.max(temperatures)
print(f"最高温度: {max_temp}°C")
# 计算最低温度
min_temp = np.min(temperatures)
print(f"最低温度: {min_temp}°C")
# 计算超过30度的天数
days_above_30 = np.sum(temperatures > 30)
print(f"超过30度的天数: {days_above_30}天")

平均温度: 29.29°C
最高温度: 32°C
最低温度: 27°C
超过30度的天数: 2天


题目2：学生成绩统计
某班学生的数学成绩：[85, 90, 78, 92, 88, 76, 95]。
- 请计算该班学生的平均分、中位数和标准差
- 将成绩转化为百分制成绩（满分100分），并找出成绩在85分以上的学生人数

In [2]:
# 学生成绩数据
scores = np.array([85, 90, 78, 92, 88, 76, 95])
# 计算平均分
average_score = np.mean(scores)
print(f"平均分: {average_score:.2f}")
# 计算中位数
median_score = np.median(scores)
print(f"中位数: {median_score}")
# 计算标准差
std_dev_score = np.std(scores)
print(f"标准差: {std_dev_score:.2f}")
# 转化为百分制成绩（假设原成绩已是百分制）
# 找出成绩在85分以上的学生人数
students_above_85 = np.sum(scores > 85)
print(f"成绩在85分以上的学生人数: {students_above_85}人")

平均分: 86.29
中位数: 88.0
标准差: 6.56
成绩在85分以上的学生人数: 4人


题目3：矩阵运算
给定两个矩阵A和B：
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]。
- 请计算矩阵A 和 B 的标量和、点积（元素对应相乘）
- 请计算矩阵A 和 B 矩阵乘法

In [3]:
# 定义矩阵A和B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
# 计算矩阵A和B的标量和
scalar_sum = A + B
print("矩阵A和B的标量和：")
print(scalar_sum)
# 计算矩阵A和B的点积（元素对应相乘）
elementwise_product = A * B
print("矩阵A和B的点积（元素对应相乘）：")
print(elementwise_product)
# 计算矩阵A和B的矩阵乘法
matrix_product = A@B
print("矩阵A和B的矩阵乘法：")
print(matrix_product)

矩阵A和B的标量和：
[[10 10 10]
 [10 10 10]
 [10 10 10]]
矩阵A和B的点积（元素对应相乘）：
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
矩阵A和B的矩阵乘法：
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


题目4：数据归一化
某数据集包含以下数值：[10, 20, 30, 40, 50]。
- 请对该数据集进行归一化处理，使得数据范围在[0, 1]之间

In [4]:
# 数据集
data = np.array([10, 20, 30, 40, 50])
# 归一化处理
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print("归一化后的数据集：")
print(normalized_data)

归一化后的数据集：
[0.   0.25 0.5  0.75 1.  ]


题目5：随机数生成
生成一个 (3, 4) 的随机整数矩阵，范围在 [0, 10) 之间。
- 计算每列的最大值和每行的最小值
- 将数组中所有奇数替换为 -1

In [7]:
# 生成随机整数矩阵
random_matrix = np.random.randint(0, 10, size=(3, 4))
print("随机整数矩阵：")
print(random_matrix)
# 计算每列的最大值
max_per_column = np.max(random_matrix, axis=0)
print("每列的最大值：")
print(max_per_column)
# 计算每行的最小值
min_per_row = np.min(random_matrix, axis=1)
print("每行的最小值：")
print(min_per_row)
# 将数组中所有奇数替换为 -1
random_matrix[random_matrix % 2 == 1] = -1
print("将奇数替换为 -1 后的矩阵：")
print(random_matrix)
# 也可以用 np.where
random_matrix = np.where(random_matrix % 2 == 1, -1, random_matrix)
print("使用 np.where 替换奇数后的矩阵：")
print(random_matrix)

随机整数矩阵：
[[8 4 9 4]
 [0 3 4 2]
 [4 7 9 6]]
每列的最大值：
[8 7 9 6]
每行的最小值：
[4 0 4]
将奇数替换为 -1 后的矩阵：
[[ 8  4 -1  4]
 [ 0 -1  4  2]
 [ 4 -1 -1  6]]
使用 np.where 替换奇数后的矩阵：
[[ 8  4 -1  4]
 [ 0 -1  4  2]
 [ 4 -1 -1  6]]


题目6：数组变形
创建一个 1到12 的一维数组，并转换为 (3,4) 的二维数组。
- 计算每行的和与每列的平均值
- 将数组展平为一维数组

In [10]:
# 一维数组
one_d_array = np.arange(1,13)
# 转换为 (3, 4) 的二维数组
two_d_array = one_d_array.reshape((3, 4))
print("二维数组：")
print(two_d_array)
# 计算每行的和
row_sums = np.sum(two_d_array, axis=1)
print("每行的和：")
print(row_sums)
# 计算每列的平均值
column_means = np.mean(two_d_array, axis=0)
print("每列的平均值：")
print(column_means)
# 将数组展平为一维数组
flattened_array = two_d_array.flatten()
print("展平后的数组：")
print(flattened_array)


二维数组：
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和：
[10 26 42]
每列的平均值：
[5. 6. 7. 8.]
展平后的数组：
[ 1  2  3  4  5  6  7  8  9 10 11 12]


题目7：唯一值与排序
给定数组：[5, 3, 8, 3, 2, 5, 7]。
- 请找出数组中的唯一值并排序
- 计算每个唯一值的出现次数

In [11]:
# 给定数组
array = np.array([5, 3, 8, 3, 2, 5, 7])
# 找出唯一值并排序
unique_values = np.unique(array)
sorted_unique_values = np.sort(unique_values)
print("唯一值并排序：")
print(sorted_unique_values)
# 计算每个唯一值的出现次数
unique_counts = np.array([np.sum(array == value) for value in sorted_unique_values])
print("每个唯一值的出现次数：")
print(unique_counts)

唯一值并排序：
[2 3 5 7 8]
每个唯一值的出现次数：
[1 2 2 1 1]


In [ ]:
# 也可以使用 np.unique 的返回值
unique_values, unique_counts = np.unique(array, return_counts=True)
print("唯一值：", unique_values)
print("每个唯一值的出现次数：", unique_counts)