In [2]:
import torch
import torch.nn as nn

In [3]:
# 定义一个全连接层
linear = nn.Linear(5, 2)

In [4]:
# 1. 常数初始化
nn.init.zeros_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)


In [5]:
nn.init.ones_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)


In [6]:
nn.init.constant_(linear.weight, 10)
print(linear.weight)

Parameter containing:
tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]], requires_grad=True)


In [7]:
# 2.秩初始化
nn.init.eye_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]], requires_grad=True)


In [8]:
# 3.正态分布初始化
nn.init.normal_(linear.weight, mean=0, std=1)
print(linear.weight)

Parameter containing:
tensor([[-0.3064,  0.0687,  0.9166, -0.1558,  0.1163],
        [ 0.5578,  0.1308,  0.1280,  0.0492,  0.4405]], requires_grad=True)


In [9]:
# 均匀分布初始化
nn.init.uniform_(linear.weight, a=-3, b=3)
print(linear.weight)

Parameter containing:
tensor([[-1.1817, -2.6962,  1.7806, -1.3936, -2.2912],
        [-0.6099, -1.8519,  0.7870,  0.4134,  0.5110]], requires_grad=True)


In [10]:
# 5.Xavier 初始化 根据输入输出神经元数量调整权重的初始范围，确保每层输出方差与输入方差相近。
# 适用于 sigmoid 和 Tanh 等激活函数，有效缓解梯度消失或梯度爆炸问题
nn.init.xavier_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-0.2515,  0.7268,  0.2493,  0.3310, -0.5081],
        [-0.1619,  0.3183,  0.2121, -1.1583,  0.0998]], requires_grad=True)


In [11]:
nn.init.xavier_uniform_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 0.6531, -0.0641, -0.1158, -0.3590, -0.1756],
        [ 0.8026, -0.6995,  0.0732, -0.3388, -0.7869]], requires_grad=True)


In [12]:
# 6. He 初始化 适用于 relu 和 relu 的变体
nn.init.kaiming_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 0.8850,  0.8896,  0.3942,  0.2332,  0.3390],
        [ 0.6469, -0.8904, -0.4169,  1.1500,  0.5215]], requires_grad=True)


In [13]:
nn.init.kaiming_uniform_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-0.0232,  0.1516, -1.0526, -0.8516, -0.0332],
        [ 0.0407,  0.3115, -0.6807, -0.2597,  0.5900]], requires_grad=True)


In [14]:
input = torch.randn(5, 3)
print(input.device)  # 默认在 cpu 上运行

cpu


In [16]:
input = torch.randn(5, 3, device='cuda')
print(input.device) # 改成在 gpu 上运行

cuda:0


In [18]:
input = torch.tensor([[1, 2, 3], [4, 5, 6]], device='cpu').to(device='cuda')
print(input.device)

cuda:0
