In [13]:
import torch
import torch.nn as nn

In [14]:
# 定义一个全连接层
linear = nn.Linear(5, 2)

In [15]:
# 1. 常数初始化
nn.init.zeros_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)


In [16]:
nn.init.ones_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)


In [17]:
nn.init.constant_(linear.weight, 10)
print(linear.weight)

Parameter containing:
tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]], requires_grad=True)


In [18]:
# 2.秩初始化
nn.init.eye_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]], requires_grad=True)


In [19]:
# 3.正态分布初始化
nn.init.normal_(linear.weight, mean=0, std=1)
print(linear.weight)

Parameter containing:
tensor([[ 2.6396, -2.4373, -1.1918, -0.0598,  1.3402],
        [ 0.7070,  1.8777,  0.1602,  0.9196, -1.4777]], requires_grad=True)


In [20]:
# 均匀分布初始化
nn.init.uniform_(linear.weight, a=-3, b=3)
print(linear.weight)

Parameter containing:
tensor([[-0.4212,  2.5862,  2.0052, -2.7598, -0.7787],
        [ 0.1070,  2.2165, -0.8053,  2.5884,  1.3938]], requires_grad=True)


In [21]:
# 5.Xavier 初始化 根据输入输出神经元数量调整权重的初始范围，确保每层输出方差与输入方差相近。
# 适用于 sigmoid 和 Tanh 等激活函数，有效缓解梯度消失或梯度爆炸问题
nn.init.xavier_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 0.0813,  0.1877, -0.5646, -0.9732,  0.1512],
        [ 0.3352, -0.3651,  0.4584, -0.7457, -1.1501]], requires_grad=True)


In [22]:
nn.init.xavier_uniform_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-0.1650,  0.0493,  0.7089, -0.7773,  0.5525],
        [-0.5125,  0.0325, -0.0455, -0.7352,  0.5030]], requires_grad=True)


In [23]:
# 6. He 初始化 适用于 relu 和 relu 的变体
nn.init.kaiming_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-0.5012, -0.9371,  0.2622, -0.4918,  0.3594],
        [-0.5216,  0.5201,  0.8026, -0.8558,  0.4376]], requires_grad=True)


In [24]:
nn.init.kaiming_uniform_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 0.0326,  0.0488, -0.3884,  0.0799,  0.6703],
        [-0.1293, -0.6928,  0.3681,  0.8157,  0.4804]], requires_grad=True)
